### ISSUE TITLE
RailItem Width/Height and arrow click to hide/show

### ISSUE THREAD

**Issue by AndreLuizNogueira** [youssefali424/AnimatedRail#5]
Any chance you add width/height to the RailItem and arrow click to hide/show event ? 

I really liked this package, but the RailItem is too big. and the click to hide/show whould improve usage on desktop apps

**Comment by youssefali424** [comment]
yes, it can be added but the click event to hide or show might be added as optional
so adding width and height to each item or all of them at once ?

**Comment by AndreLuizNogueira** [comment]
> yes, it can be added but the click event to hide or show might be added as optional so adding width and height to each item or all of them at once ?

I believe that all at once is better. but in item someone else can make one item bigger than the others

**Comment by youssefali424** [comment]
i do believe that adding static height and width would not be perfect
so more customizations will be added and a builder for the items

**Comment by youssefali424** [comment]
done with new version 2.0.0

**Comment by AndreLuizNogueira** [comment]
> done with new version 2.0.0

thank you, you were really fast. The Click event and the width worked fine. 

I didn't undestood the usage of the builder, could you update the readme/exemple app ?

I found some bugs:

changing iconColor on RailTileConfig also changes label color when you don't pass the color in the textStyles;

when using direction: TextDirection.rtl, on hiding the rail is using opposite direction, and stays like that:
![image](https://user-images.githubusercontent.com/11053810/228360970-3e285591-d24b-411b-887a-1e4a06a281f5.png)

**Comment by youssefali424** [comment]
- "changing iconColor on RailTileConfig also changes label color when you don't pass the color in the textStyles" this is intentional,
- the builder allows you to add custom widget for the items 
- the directional part i will have to fix it in next version this is probably a bug

**Comment by youssefali424** [comment]
direction fix now added in 2.0.1
