### ISSUE TITLE
expand && maxWidth > width

### ISSUE THREAD

**Issue by imustafajamal** [youssefali424/AnimatedRail#6]
How can I solve this error in AnimatedRail package ?
When I change expand to false I get this error 

`The following assertion was thrown building MyHomePage(dirty, state: _MyHomePageState#8784e):
'package:animated_rail/animated_rail/animated_rail.dart': Failed assertion: line 57 pos 16: 'expand && maxWidth > width': is not true.`

**Comment by youssefali424** [comment]
solved check latest version
